use crate::model::UsbDeviceRecord;
use std::sync::mpsc::Receiver;

/// Device lifecycle events for hotplug monitoring.
/// 
/// These events represent state changes in the device detection system:
/// - `Added`: New device has completed detection pipeline and is confirmed
/// - `Removed`: Previously confirmed device has disconnected from bus
/// - `Changed`: Device state modified (driver binding, health status, etc.)
/// 
/// Events are generated by platform-specific watchers and sent via channels
/// to application code for reactive handling.
#[derive(Debug, Clone)]
pub enum DeviceEvent {
    /// Device connected and confirmed (ready for use)
    Added(UsbDeviceRecord),
    /// Device disconnected (no longer accessible)
    Removed(UsbDeviceRecord),
    /// Device state changed (driver, health, etc.)
    Changed(UsbDeviceRecord),
}

/// Trait for real-time USB device hotplug monitoring.
/// 
/// DeviceWatcher implementations use platform-specific notification mechanisms
/// to detect USB device connection and disconnection events:
/// - Linux: udev monitoring
/// - Windows: Device notification API
/// - macOS: IOKit notifications
/// 
/// Watchers run on a separate thread and send DeviceEvent messages via a channel.
/// Applications receive events and handle them reactively.
/// 
/// # Thread Safety
/// Watchers are thread-safe and designed to run concurrently with device enumeration.
/// The start() method spawns a background thread, and stop() terminates it gracefully.
pub trait DeviceWatcher: Send + Sync {
    /// Start monitoring for device events. Returns a receiver for event messages.
    /// 
    /// The watcher will run on a background thread until stop() is called.
    fn start(&mut self) -> Result<Receiver<DeviceEvent>, Box<dyn std::error::Error>>;
    
    /// Stop monitoring and shut down the background thread.
    fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>>;
}

#[cfg(target_os = "linux")]
pub mod linux;
#[cfg(target_os = "macos")]
pub mod macos;
#[cfg(target_os = "windows")]
pub mod windows;

// Re-export platform-specific watcher
#[cfg(target_os = "linux")]
pub use linux::LinuxDeviceWatcher as PlatformWatcher;
#[cfg(target_os = "macos")]
pub use macos::MacOSDeviceWatcher as PlatformWatcher;
#[cfg(target_os = "windows")]
pub use windows::WindowsDeviceWatcher as PlatformWatcher;
